import Link from "next/link";
import Layout from "pages/Layout";

const IndexPage = () => (
  <Layout 
    title="Minecraft PvP al Máximo Nivel | Blotcraft Oficial"
    description="Únete a Blotcraft, el servidor de Minecraft PvP en español donde el combate es intenso, la competencia es real y cada partida cuenta. ¡Entra ahora y demuestra tu habilidad!"
  >
    <section>
      <h1 className="text-title">Hello Next.js</h1>
      <h2 className="text-description">Blotcraft - prueba tailwind</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed libero, laboriosam dolore obcaecati eaque molestiae id exercitationem natus nobis animi error? Voluptas ut, placeat omnis, totam unde tempore ipsa reiciendis, nisi voluptatum eaque a. Est soluta impedit ea? Quia sunt temporibus numquam minus labore pariatur! A alias cum atque fugiat, illum ratione deserunt vitae laudantium aperiam culpa quibusdam ipsum itaque non harum tenetur voluptate officiis beatae est illo ab. Rem recusandae accusantium harum earum, quisquam inventore consequatur tenetur quod, voluptas sed dolorem necessitatibus similique nobis. Voluptate, perferendis rerum! Odio eveniet obcaecati pariatur necessitatibus incidunt nihil dignissimos ipsum excepturi asperiores inventore, expedita eaque quo labore at consequuntur numquam eos fugit iste perferendis perspiciatis voluptates vel commodi voluptate quam. Ad numquam necessitatibus id, ipsam eveniet iure error quos et ipsa. Iure, dolor! Deleniti aut dolorum provident quidem iusto at, cumque blanditiis odio totam dolor consectetur nisi molestiae libero! Excepturi eaque fuga laudantium at, pariatur aliquid possimus repellat a autem rerum quo facilis aperiam, atque unde tenetur? Ipsa asperiores aperiam ducimus molestias optio voluptatibus laborum eligendi possimus dicta aliquid quo unde ullam voluptates reiciendis rem magni at officia assumenda ipsam ex quam libero, vel reprehenderit similique. Deleniti autem corrupti quo rerum eaque itaque?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed libero, laboriosam dolore obcaecati eaque molestiae id exercitationem natus nobis animi error? Voluptas ut, placeat omnis, totam unde tempore ipsa reiciendis, nisi voluptatum eaque a. Est soluta impedit ea? Quia sunt temporibus numquam minus labore pariatur! A alias cum atque fugiat, illum ratione deserunt vitae laudantium aperiam culpa quibusdam ipsum itaque non harum tenetur voluptate officiis beatae est illo ab. Rem recusandae accusantium harum earum, quisquam inventore consequatur tenetur quod, voluptas sed dolorem necessitatibus similique nobis. Voluptate, perferendis rerum! Odio eveniet obcaecati pariatur necessitatibus incidunt nihil dignissimos ipsum excepturi asperiores inventore, expedita eaque quo labore at consequuntur numquam eos fugit iste perferendis perspiciatis voluptates vel commodi voluptate quam. Ad numquam necessitatibus id, ipsam eveniet iure error quos et ipsa. Iure, dolor! Deleniti aut dolorum provident quidem iusto at, cumque blanditiis odio totam dolor consectetur nisi molestiae libero! Excepturi eaque fuga laudantium at, pariatur aliquid possimus repellat a autem rerum quo facilis aperiam, atque unde tenetur? Ipsa asperiores aperiam ducimus molestias optio voluptatibus laborum eligendi possimus dicta aliquid quo unde ullam voluptates reiciendis rem magni at officia assumenda ipsam ex quam libero, vel reprehenderit similique. Deleniti autem corrupti quo rerum eaque itaque?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed libero, laboriosam dolore obcaecati eaque molestiae id exercitationem natus nobis animi error? Voluptas ut, placeat omnis, totam unde tempore ipsa reiciendis, nisi voluptatum eaque a. Est soluta impedit ea? Quia sunt temporibus numquam minus labore pariatur! A alias cum atque fugiat, illum ratione deserunt vitae laudantium aperiam culpa quibusdam ipsum itaque non harum tenetur voluptate officiis beatae est illo ab. Rem recusandae accusantium harum earum, quisquam inventore consequatur tenetur quod, voluptas sed dolorem necessitatibus similique nobis. Voluptate, perferendis rerum! Odio eveniet obcaecati pariatur necessitatibus incidunt nihil dignissimos ipsum excepturi asperiores inventore, expedita eaque quo labore at consequuntur numquam eos fugit iste perferendis perspiciatis voluptates vel commodi voluptate quam. Ad numquam necessitatibus id, ipsam eveniet iure error quos et ipsa. Iure, dolor! Deleniti aut dolorum provident quidem iusto at, cumque blanditiis odio totam dolor consectetur nisi molestiae libero! Excepturi eaque fuga laudantium at, pariatur aliquid possimus repellat a autem rerum quo facilis aperiam, atque unde tenetur? Ipsa asperiores aperiam ducimus molestias optio voluptatibus laborum eligendi possimus dicta aliquid quo unde ullam voluptates reiciendis rem magni at officia assumenda ipsam ex quam libero, vel reprehenderit similique. Deleniti autem corrupti quo rerum eaque itaque?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed libero, laboriosam dolore obcaecati eaque molestiae id exercitationem natus nobis animi error? Voluptas ut, placeat omnis, totam unde tempore ipsa reiciendis, nisi voluptatum eaque a. Est soluta impedit ea? Quia sunt temporibus numquam minus labore pariatur! A alias cum atque fugiat, illum ratione deserunt vitae laudantium aperiam culpa quibusdam ipsum itaque non harum tenetur voluptate officiis beatae est illo ab. Rem recusandae accusantium harum earum, quisquam inventore consequatur tenetur quod, voluptas sed dolorem necessitatibus similique nobis. Voluptate, perferendis rerum! Odio eveniet obcaecati pariatur necessitatibus incidunt nihil dignissimos ipsum excepturi asperiores inventore, expedita eaque quo labore at consequuntur numquam eos fugit iste perferendis perspiciatis voluptates vel commodi voluptate quam. Ad numquam necessitatibus id, ipsam eveniet iure error quos et ipsa. Iure, dolor! Deleniti aut dolorum provident quidem iusto at, cumque blanditiis odio totam dolor consectetur nisi molestiae libero! Excepturi eaque fuga laudantium at, pariatur aliquid possimus repellat a autem rerum quo facilis aperiam, atque unde tenetur? Ipsa asperiores aperiam ducimus molestias optio voluptatibus laborum eligendi possimus dicta aliquid quo unde ullam voluptates reiciendis rem magni at officia assumenda ipsam ex quam libero, vel reprehenderit similique. Deleniti autem corrupti quo rerum eaque itaque?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed libero, laboriosam dolore obcaecati eaque molestiae id exercitationem natus nobis animi error? Voluptas ut, placeat omnis, totam unde tempore ipsa reiciendis, nisi voluptatum eaque a. Est soluta impedit ea? Quia sunt temporibus numquam minus labore pariatur! A alias cum atque fugiat, illum ratione deserunt vitae laudantium aperiam culpa quibusdam ipsum itaque non harum tenetur voluptate officiis beatae est illo ab. Rem recusandae accusantium harum earum, quisquam inventore consequatur tenetur quod, voluptas sed dolorem necessitatibus similique nobis. Voluptate, perferendis rerum! Odio eveniet obcaecati pariatur necessitatibus incidunt nihil dignissimos ipsum excepturi asperiores inventore, expedita eaque quo labore at consequuntur numquam eos fugit iste perferendis perspiciatis voluptates vel commodi voluptate quam. Ad numquam necessitatibus id, ipsam eveniet iure error quos et ipsa. Iure, dolor! Deleniti aut dolorum provident quidem iusto at, cumque blanditiis odio totam dolor consectetur nisi molestiae libero! Excepturi eaque fuga laudantium at, pariatur aliquid possimus repellat a autem rerum quo facilis aperiam, atque unde tenetur? Ipsa asperiores aperiam ducimus molestias optio voluptatibus laborum eligendi possimus dicta aliquid quo unde ullam voluptates reiciendis rem magni at officia assumenda ipsam ex quam libero, vel reprehenderit similique. Deleniti autem corrupti quo rerum eaque itaque?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed libero, laboriosam dolore obcaecati eaque molestiae id exercitationem natus nobis animi error? Voluptas ut, placeat omnis, totam unde tempore ipsa reiciendis, nisi voluptatum eaque a. Est soluta impedit ea? Quia sunt temporibus numquam minus labore pariatur! A alias cum atque fugiat, illum ratione deserunt vitae laudantium aperiam culpa quibusdam ipsum itaque non harum tenetur voluptate officiis beatae est illo ab. Rem recusandae accusantium harum earum, quisquam inventore consequatur tenetur quod, voluptas sed dolorem necessitatibus similique nobis. Voluptate, perferendis rerum! Odio eveniet obcaecati pariatur necessitatibus incidunt nihil dignissimos ipsum excepturi asperiores inventore, expedita eaque quo labore at consequuntur numquam eos fugit iste perferendis perspiciatis voluptates vel commodi voluptate quam. Ad numquam necessitatibus id, ipsam eveniet iure error quos et ipsa. Iure, dolor! Deleniti aut dolorum provident quidem iusto at, cumque blanditiis odio totam dolor consectetur nisi molestiae libero! Excepturi eaque fuga laudantium at, pariatur aliquid possimus repellat a autem rerum quo facilis aperiam, atque unde tenetur? Ipsa asperiores aperiam ducimus molestias optio voluptatibus laborum eligendi possimus dicta aliquid quo unde ullam voluptates reiciendis rem magni at officia assumenda ipsam ex quam libero, vel reprehenderit similique. Deleniti autem corrupti quo rerum eaque itaque?</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed libero, laboriosam dolore obcaecati eaque molestiae id exercitationem natus nobis animi error? Voluptas ut, placeat omnis, totam unde tempore ipsa reiciendis, nisi voluptatum eaque a. Est soluta impedit ea? Quia sunt temporibus numquam minus labore pariatur! A alias cum atque fugiat, illum ratione deserunt vitae laudantium aperiam culpa quibusdam ipsum itaque non harum tenetur voluptate officiis beatae est illo ab. Rem recusandae accusantium harum earum, quisquam inventore consequatur tenetur quod, voluptas sed dolorem necessitatibus similique nobis. Voluptate, perferendis rerum! Odio eveniet obcaecati pariatur necessitatibus incidunt nihil dignissimos ipsum excepturi asperiores inventore, expedita eaque quo labore at consequuntur numquam eos fugit iste perferendis perspiciatis voluptates vel commodi voluptate quam. Ad numquam necessitatibus id, ipsam eveniet iure error quos et ipsa. Iure, dolor! Deleniti aut dolorum provident quidem iusto at, cumque blanditiis odio totam dolor consectetur nisi molestiae libero! Excepturi eaque fuga laudantium at, pariatur aliquid possimus repellat a autem rerum quo facilis aperiam, atque unde tenetur? Ipsa asperiores aperiam ducimus molestias optio voluptatibus laborum eligendi possimus dicta aliquid quo unde ullam voluptates reiciendis rem magni at officia assumenda ipsam ex quam libero, vel reprehenderit similique. Deleniti autem corrupti quo rerum eaque itaque?</p>
    </section>
  </Layout>
);

export default IndexPage;
